<?php
$rental = [
    [
        'id' => 1,
        'name' => 'Innova Reborn',
        'Harga' => 'Rp 900.000 / hari',
        'image' => 'https://lh3.googleusercontent.com/d/1jihhp_IVRI_-89JBl_aGQVqOUhNZ9-mH',
        'seat' => '7 Seats',
        'transmisi' => 'Automatic',
    ],
    [
        'id' => 2,
        'name' => 'New Avanza',
        'Harga' => 'Rp 600.000 / hari',
        'image' => 'https://lh3.googleusercontent.com/d/1Vuz-8QLmSJQ75ltQx8TCxK8ISKisyTfF',
        'seat' => '7 Seats',
        'transmisi' => 'Manual',
    ],
    [
        'id' => 3,
        'name' => 'Innova Zenix',
        'Harga' => 'Rp 900.000 / hari',
        'image' => 'https://lh3.googleusercontent.com/d/15DhkwfL8SSEn1kLiYvlOlYbjb3loBxfd',
        'seat' => '7 Seats',
        'transmisi' => 'Automatic',
    ],
    [
        'id' => 4,
        'name' => 'Fortuner GR',
        'Harga' => 'Rp 1.500.000 / hari',
        'image' => 'https://lh3.googleusercontent.com/d/1YC0_xXA5wQgu_6_xer23uWDiv4YFg2bc',
        'seat' => '7 Seats',
        'transmisi' => 'Automatic',
    ],
    [
        'id' => 5,
        'name' => 'Alphard',
        'Harga' => 'Rp 2.000.000 / hari',
        'image' => 'https://lh3.googleusercontent.com/d/1IGk04E_iudsFDAf3xwWmUskCaJIL7UKX',
        'seat' => '7 Seats',
        'transmisi' => 'Automatic',
    ],
    [
        'id' => 6,
        'name' => 'Hiace Premio',
        'Harga' => 'Rp 1.750.000 / hari',
        'image' => 'https://lh3.googleusercontent.com/d/1011Q3YU7pYE94Z6rumR3_jwviPSLl4hp',
        'seat' => '14 Seats',
        'transmisi' => 'Automatic',
    ],
    [
        'id' => 7,
        'name' => 'Hiace Commuter',
        'Harga' => 'Rp 1.500.000 / hari',
        'image' => 'https://lh3.googleusercontent.com/d/138shc06A6e8qkBfH_5sInN1TKaLUnp_Z',
        'seat' => '14 Seats',
        'transmisi' => 'Manual',
    ],
    [
        'id' => 8,
        'name' => 'Medium Bus',
        'Harga' => 'Rp 2.000.000 / hari',
        'image' => 'https://lh3.googleusercontent.com/d/1YpScMSVpxbbpnLNTRW4g8MF4ODuCHU8X',
        'seat' => '30 Seats',
        'transmisi' => 'Manual',
    ],
    [
        'id' => 9,
        'name' => 'Big Bus',
        'Harga' => 'Rp 3.000.000 / hari',
        'image' => 'https://lh3.googleusercontent.com/d/1BHGKSqLyb8NpjoUqlqyoIFrtqIQ6wulx',
        'seat' => '50 Seats',
        'transmisi' => 'Manual',
    ],
];
?>
